id: IF234EA32
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T02:47:39+00:00'
last_modified: '2022-06-08T04:57:33.853283+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12420
  title: ལཱ་མོ་ཚ་ཀན་ནོ་མོན་ཧན་ཧོ་ཐོག་ཐུ་ཚང་གི་རྣམ་པར་ཐར་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4F63:
      image_group_id: I1KG12445
      title: ''
      total_pages: 304
      order: 1
      base_file: 4F63.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
